ExplorePrizePoolsHeader: Styled Dismissable Info + Buttons
pooltogether/v4-ui pull request #101
Opened 2022-11-10 19:16 UTC by Ncookiez

- Styled explainer section for desktop and mobile.
- The section can now be dismissed and brought back up through buttons.

By default, the explanation will be displayed with a 'Dismiss' button in its bottom-right. If clicked, the explanation will be hidden and instead a "How does this work?" button will be displayed instead. Was debating the position of this button, but it looks decent left-aligned as of now imo.

### Desktop:

![image](https://user-images.githubusercontent.com/22108522/201185971-7691d687-4603-4de8-814a-bba05d2f2c50.png)

![image](https://user-images.githubusercontent.com/22108522/201186018-69ac3318-66fe-4c07-809f-fd14e8ce1306.png)

### Mobile:

![image](https://user-images.githubusercontent.com/22108522/201186082-cbb89689-5b32-4912-9e96-3edad8d6d229.png)

![image](https://user-images.githubusercontent.com/22108522/201186108-4d9b847f-d759-467f-b83d-15eec0478274.png)

2022-11-10 20:32 UTC, dylandesrosier requested changes

2022-11-10 20:32 UTC, dylandesrosier commented on src/components/ModalViews/ExplorePrizePoolsView/ExplorePrizePoolsHeader.tsx
> +        How does this work?
Localize!

2022-11-10 20:32 UTC, dylandesrosier commented on src/components/ModalViews/ExplorePrizePoolsView/ExplorePrizePoolsHeader.tsx
> +        Dismiss
Localize!

2022-11-11 14:36 UTC, Ncookiez commented on src/components/ModalViews/ExplorePrizePoolsView/ExplorePrizePoolsHeader.tsx
> +        How does this work?
Fixed through ed8e1f1!

2022-11-11 14:36 UTC, Ncookiez commented on src/components/ModalViews/ExplorePrizePoolsView/ExplorePrizePoolsHeader.tsx
> +        Dismiss
Fixed through ed8e1f1!

2022-11-28 14:43 UTC, dylandesrosier approved these changes

2022-11-28 14:43 UTC, merged