Pool 1849 -  display delegated amounts
pooltogether/v4-ui pull request #48
Opened 2022-03-02 00:07 UTC by chuckbergeron

2022-03-03 14:32 UTC, dylandesrosier requested changes
`0x856Bf74e6a12E398699d366d5C9F743854603e0D` is a test wallet that was sent 100 tickets without delegating. It's showing that they have -100 delegated to them. We'll need to check their delegate before subtracting their balance. Similarly for accounts that are delegating their balance - the ticket balance should only be subtracted when they are delegating to themselves. All of these checks will need to be done per chain.

Should this component only render if the user has an amount delegated to them? Majority of users will see "Total delegated to you - $0" all of the time in some prime real estate.

2022-03-03 14:32 UTC, dylandesrosier commented on src/views/Account/AccountCard/BalanceDelegatedTo.tsx
> +              id={`tooltip-vapr`}
Tool tip needs a unique id

2022-03-03 14:32 UTC, dylandesrosier commented on src/views/Account/AccountCard/BalanceDelegatedTo.tsx
> +  const debugBox = (
🗑

2022-03-03 14:32 UTC, dylandesrosier commented on src/views/Account/AccountCard/BalanceDelegatedTo.tsx
> +          <span className='font-bold text-xl mb-1'>${delegatedToAmount}</span>
nit: round this number to 2 decimals

2022-03-03 23:20 UTC, chuckbergeron commented
<img width="646" alt="Screen Shot 2022-03-03 at 3 20 25 PM" src="https://user-images.githubusercontent.com/35717/156669497-c96e1d4f-e3b1-4bd5-aacd-9dc54cd49296.png">

2022-03-04 19:43 UTC, dylandesrosier approved these changes

2022-03-04 19:43 UTC, dylandesrosier commented on src/views/Account/V4Deposits/BalanceDelegatedTo.tsx
> +            $<CountUp countTo={numberWithCommas(delegatedToAmount)} />
`CountUp` handles adding the commas, you need to pass just `countTo={delegatedToAmount}` otherwise it renders `0.0` for everything

2022-03-04 19:43 UTC, dylandesrosier commented on src/views/Account/V4Deposits/BalanceDelegatedTo.tsx
> +    delegatedToAmount = formatUnits(usersTotalV4TwabBalanceUnformatted, 6)
You can use `usePrizePoolTokens` and pull the decimals from there rather than hardcoding for USDC

2022-03-04 19:43 UTC, dylandesrosier commented on src/views/Account/V4Deposits/BalanceDelegatedTo.tsx
> +          {/* <FeatherIcon icon='chevron-right' className='my-auto w-6 h-6 opacity-50' /> */}
🗑

2022-03-04 21:42 UTC, merged